### ISSUE TITLE
ciri: default conf (from readme) stopped working

### ISSUE THREAD

**Issue by alon-e** [iotaledger/entangled#1054]
since https://github.com/iotaledger/entangled/commit/1861c9f6d1f4d4a037b88e1fc2df266a83432d7d
running a node with:
```
bazel run --define network=mainnet -- ciri
```
shows the usage and exits - reverting the commit, the node starts fine.

**Comment by thibault-martinez** [comment]
Hi @alon-e, it seems to work fine on my side.
However I did change the name of some options so I believe your `conf.yml` is not up-to-date.
I suspect:
- `coordinator` is now `coordinator-address`
- `num-keys-in-milestone` is now `coordinator-depth`

Please let me know if that work.

**Comment by thibault-martinez** [comment]
I'll add a better error message than the usage for this kind of scenario.

**Comment by thibault-martinez** [comment]
Hi @alon-e, following https://github.com/iotaledger/entangled/pull/1100, `conf.yml` is not tracked by git anymore. We provide a `conf.example.yml` that can be renamed.
Please update us if my previous message fixes your issue.

**Comment by thibault-martinez** [comment]
This has been fixed. Please reopen if you still have issues.
