### ISSUE TITLE
Windows Build fails with addition of libmicrohttpd

### ISSUE THREAD

**Issue by obany** [iotaledger/entangled#1056]
With the addition of libmicrohttpd for use by the apis the build no longer works on Windows platforms.

```
Starting local Bazel server and connecting to it...
ERROR: C:/users/marty/_bazel_marty/6yfoefmv/external/libmicrohttpd/BUILD.bazel:248:1: in cc_import rule @libmicrohttpd//:libmicrohttpd_shared: 'interface library' must be specified when using cc_import for shared library on Windows
ERROR: Analysis of target '//ciri:ciri' failed; build aborted: Analysis of target '@libmicrohttpd//:libmicrohttpd_shared' failed; build aborted
INFO: Elapsed time: 9.490s
INFO: 0 processes.
```

**Comment by l3utterfly** [comment]
Can be fixed by changing your cached bazel external library in:

C:\Users\[username]\_bazel_[username]\[random id]\external\libmicrohttpd\BUILD.bazel

Add `interface_library = "libmicrohttpd.lib",` to line 250

I believe a permanent fix relies on libmicrohttpd package to be updated on their side

**Comment by oopsmonk** [comment]
it's fixed in https://github.com/iotaledger/rules_iota/commit/861a1243beef7b69f4ac1e9179327f959b4f7ddb
