### ISSUE TITLE
utils: investigate current_timestamp_ms failure on Windows

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#1116]

**Comment by oopsmonk** [comment]
Can you describe or give more info about this error?

**Comment by thibault-martinez** [comment]
Trinity team reported that the `attachmentTimestamp` on Windows was invalid. There was indeed an error where `current_timestamp_ms` only returned milliseconds of the current minute. It is now fixed and tested by Trinity team in #1122 .
