### ISSUE TITLE
consensus: remove snapshot internal locking

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#1143]
I actually think no snapshot function should internally take lock. Snapshot locking should be users responsibility only.

_Originally posted by @thibault-martinez in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjMwNTY3Mzg3/pull_request_reviews/more_threads_

**Comment by tsvisabo** [comment]
done

**Comment by tsvisabo** [comment]
some functions should and does take lock..
and if no function that takes a lock should be called from another `iota_snapshot_` function, because then we can lock multiple times, instead, we should implement `_no_lock` version
