### ISSUE TITLE
CClient: includes incorrect

### ISSUE THREAD

**Issue by kuhlmannmarkus** [iotaledger/entangled#1148]
**Describe the bug**
The includes in entangled/cclient/types/types.h are incorrect. Most hash-related headers are not present anymore (i.e. utils/containers/hash/hash243_queue.h).
The project builds fine, although its impossible for me to use cclient in my project, due to this.

**To Reproduce**
1. look at entangled/cclient/types/types.h

**Comment by oopsmonk** [comment]
those header files are generated through bazel build system.

**Comment by kuhlmannmarkus** [comment]
I see. Thank you!
