### ISSUE TITLE
cclient: hash243_queue json deserialization wrong response

### ISSUE THREAD

**Issue by MaksymPelishko** [iotaledger/entangled#1240]
When I used the extended API function "getNewAddress" and set [address_opt_t].total to 0 value I had an infinite process. This happens because we receiving empty hashes array if address not used yet and then "json_array_to_hash243_queue" function in cclient/serialization/json/helpers.c file returns RC_ERROR when we deserialize response from the server. In result, the program continues generating new addresses.

To reproduce you just need to use "getNewAddress" extended API function and set parameter [address_opt_t].total to 0(to get the list of all used addresses with first unused).

**Comment by oopsmonk** [comment]
@MaksymPelishko thanks, it's fixed in https://github.com/iotaledger/entangled/pull/1249
