### ISSUE TITLE
utils: harmonize containers API

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#1256]
Mostly ensure that non-modifying functions doesn't take a pointer to the container.

**Comment by howjmay** [comment]
is there anyone working on this issue? if not, could I take it?

**Comment by thibault-martinez** [comment]
Hi @HowJMay, you can take it :)
Basically, this issue is about:
- Checking that similar functions have a similar prototype across all containers
- Checking that we don't pass pointers when not needed
- Ensure constness
- (Maybe some formatting since clang-format doesn't pass on it because of the files extensions)

**Comment by thibault-martinez** [comment]
Fixed by https://github.com/iotaledger/entangled/pull/1314
