### ISSUE TITLE
ciri: OOM with local snapshots

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#1261]
cIRI gets killed with the following when local snapshots is enabled.

```
==18509==ERROR: AddressSanitizer failed to allocate 0x10000 (65536) bytes of memory at address 0x60d086f60 (error code: 12)
ERROR: Failed to mmap
```

**Comment by tsvisabo** [comment]
how can i reproduce?
does that happen on startup or after a while?

**Comment by thibault-martinez** [comment]
Just run cIRI with LS and the LS files on the server and it'll eventually crash
