### ISSUE TITLE
Transaction assert failed during finalizing mam bundle

### ISSUE THREAD

**Issue by wusyong** [iotaledger/entangled#1300]
**Describe the bug**
After mam bundle is wrapped up, finalize it will get error about assert failed.
```
Assertion failed: (transaction->loaded_columns_mask.essence & MASK_ESSENCE_OBSOLETE_TAG), function transaction_obsolete_tag, file external/entangled/common/model/transaction.h, line 253.
```
The reason I think is because of commit [`ebdbb14`](https://github.com/iotaledger/entangled/commit/ebdbb14210ea86abca0834f546343f3d2ae13916#diff-240664de4f90d345f0d6534d3044ff7eL40). If there's only `transaction_reset`, mask of value and obsolete tag won't be set.

**To Reproduce**
While I'm not sure why examples under mam work fine. But if I just construct a mam bundle using mam api outside of this workspace, it will have this assertion fail error.

**Expected behavior**
Bundle finalizes correctly.

**Comment by thibault-martinez** [comment]
Hi @wusyong , you're right, thanks! We'll fix that ASAP.
