### ISSUE TITLE
cIRI: Dockerfile

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/entangled#1353]
providing a Dockerfile for running cIRI in a container.

**Comment by wusyong** [comment]
Is this issue assigned yet? If not, I would like to implement with `rules_docker`.

**Comment by oopsmonk** [comment]
> Is this issue assigned yet? If not, I would like to implement with `rules_docker`.

@wusyong I just started to work on this issue yesterday, you can assign to yourself if you are interested in it. let me know if you want to solve it, thanks  :-)

**Comment by wusyong** [comment]
Thanks! I'll give it a try.
