### ISSUE TITLE
Cryptographic functions should use flex_trits

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#136]
> We should probably stop the flex_trits at the ISS layer, and have curl_/kerl_* continue to work on trits.

> Not sure that they do. It would be nice to reduce the amount of trit_t  that regular users are exposed to though

> So it's a nice-to-have but not a must?

> (note that ISS should pretty much never be used outside of entangled-internal tools, so this is up to us at the end)

> I feel like there could be less code duplication if we do it inside than outside, but I don't think that's high priority atm

> Not just code duplication but also memory usage reduction, a flex-trit interface would enable only converting a single slice at a time

**Comment by ifullgaz** [comment]
Is it similar to Issue #32?
