### ISSUE TITLE
Node storage abstraction layer

### ISSUE THREAD

**Issue by th0br0** [iotaledger/entangled#14]
Different deployment targets require different storage backends for a functioning IOTA node.
As such, we need to abstract the actual storage layer for higher-level (i.e. networking operations)

* [ ] Design storage abstraction layer
This can be as simple as 
```c
extern retcode_t iota_stor_store(const trit_array_p hash /* = key */, const trit_array_p value /* = tx data */);
extern retcode_t iota_stor_load(const trit_array_p hash /* = key */, trit_array_p into);
```

However, we also need to have a means of storing metadata (e.g. arrival time, consensus data, ...)

```c
extern retcode_t iota_stor_metadata_store(const trit_array_p hash, const trit_array_p metadataKey, const trit_array_p value); 
extern retcode_t iota_stor_metadata_load(const trit_array_p hash, const trit_array_p metadataKey,  trit_array_p into); 
```

Questions:
- Where and how is concurrency handled?
- Do we need to store more than this? IRI has 5 different 'tables' or so

* [ ] Implement storage abstraction layer
- Do we need helper methods here? Probably for transaction stuff at the least.
* [ ] Implement in-memory storage
- Just do a `std::unorderd_map`?

*Potential users:*
- TangleScope

**Comment by thibault-martinez** [comment]
Here are some preliminary thoughts.

## Design storage abstraction layer

IRI has the following view models:
- AddressViewModel
- ApproveeViewModel
- BundleViewModel
- HashesViewModel
- MilestoneViewModel
- StateDiffViewModel
- TagViewModel
- TipsViewModel
- TransactionViewModel

Knowing if we need to store more than transactions will influence the API design.
- If yes,  a lot of common code amongst different models could be handled by macros or function pointers.
- If no, your example could be sufficient.

A simple `findTransactions` would actually need BundleViewModel, AddressViewModel, TagViewModel and ApproveeViewModel in addition to the obviously needed TransactionViewModel.

I think we should consider different models from the very beginning.

## Implement storage abstraction layer

- Hash-based models (AddressViewModel, ApproveeViewModel, BundleViewModel, HashesViewModel, TagViewModel): I don't think there is a need for helper functions.
- Others, if implemented (MilestoneViewModel, StateDiffViewModel, TipsViewModel, TransactionViewModel): there might be a need for helper functions.

## Implement in-memory storage

### Option 1: std::unorderd_map

- Simple
- Need to handle concurrency
- No external dependency

### Option 2: KV Engine

- Optimized for byte streams
- Thread-safe
- External dependency

Engines likes RocksDB or LevelDB provides underlying C APIs

**Comment by tsvisabo** [comment]
So done..
