### ISSUE TITLE
Deserialize response buffer into an opaque (void*) output buffer  

### ISSUE THREAD

**Issue by tsvisabo** [iotaledger/entangled#143]
I am laying it out here what we discussed @oopsmonk ,
client's user/client should allocate memory into an opaque address
And that should be used for deserialization, because we can not be sure how much memory should be allocated to each field before we do parsing
for example we should change `json_get_balances_deserialize_response`  to:
`void json_get_balances_deserialize_response(const serializer_t* const s, const char* const obj, void* out, size_t outSize) `

**Comment by th0br0** [comment]
Make sure to `memset` the area before writing to it ;) 
Sounds like a sane change though. That'll also allow for a static outbuffer and - once some kind of pagination is supported on IRI - pagination.

**Comment by oopsmonk** [comment]
I tried to do what we discussed. Considering the memory block which allocated by the user, 
here is the scenario that I can picture. 
```
char* req = (char*)malloc(1000*sizeof(char));
char* res = (char*)malloc(1000*sizeof(char));
//have to provide init function and configure method.
init_get_balances_res(res);
init_get_balances_req(req);
iota_api_get_balances(service, req, res);
// user doesn't know how to fetch an opaque buffer. need provide something like 
// get_balances, get_references...
```
regarding with `utarray` can do that kind of things, we can use it as well. 
```
get_balances_req_t* req;
get_balances_res_t* res;
init_get_balances_req(req); // using utarray to allocat
init_get_balances_res(res);
iota_api_get_balances(service, req, res);
// user can fetch data via structure and readable 
```

**Comment by tsvisabo** [comment]
In the first example (opaque), what does `init_get_balances_res` do?
why `iota_api_get_balances(service, req, res);`?
can't a user cast the buffer  to `get_balances_res_t` ?

**Comment by oopsmonk** [comment]
A user can cast a buffer to a structure, but thinking about the response with unpredictable content length, utarray can extent buffer with no problem. 
For the platform without malloc/realloc, we might do an opaque way to handle memory, the memory block and size will depend on the platform. This kind of devices will have some issue, 1) if we occupied a large of memory statically, there will have the OOM problem in JSON parser, HTTP service, or other applications. 2) if we have a custom memory pool, we need deal with the fragmentation issue, especially the device has small memory.

**Comment by oopsmonk** [comment]
@tsvisabo do you agree to close it? I think is not a problem in the current codebase.
