### ISSUE TITLE
Storage - Add/Modify methods to load (Find) by key subset 

### ISSUE THREAD

**Issue by tsvisabo** [iotaledger/entangled#160]
For example:
`iota_stor_load_hashes_approvers`
`iota_stor_load_hashes`
81 trytes is way too much for guaranteeing that a records is unique.

**Comment by th0br0** [comment]
Could you explain why you consider this an issue? Also note that, with 5 trits per byte we're only looking at 49bytes.

Keep in mind that if you truncate the lookup, you'll need to implement logic for handling multiple returns etc?

**Comment by tsvisabo** [comment]
When doing a DFS/BFS on the tangle starting from  an entry point,
there is no need to keep the entire hash of each tx of the cone we get from the search
but you are correct, i don't see it as a major issue at all.

**Comment by tsvisabo** [comment]
not relevant
