### ISSUE TITLE
Rollback bounds check in int8_to_flex_trit_array

### ISSUE THREAD

**Issue by ifullgaz** [iotaledger/entangled#172]
The bounds checking statement needs to be reinstated as per previous code:
```if (num_trits > len)``` =>  ```if (num_trits > len || num_trits > to_len)```

**Comment by thibault-martinez** [comment]
Thanks @ifullgaz, it is included in my next PR.

**Comment by ifullgaz** [comment]
Oh! Sorry about that!

**Comment by thibault-martinez** [comment]
No worries !
