### ISSUE TITLE
Consensus components implementation

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#182]
- [x] cw_rating_calculator (#142)
- [x] entry_point_selector (#180)
- [x] ledger_validator (#181)
- [x] milestone_tracker (#214)
- [x] snapshot (#280)
- [x] tangle (#142)
- [x] transaction_validator (#144)
- [x] walker (#178)
- [x] walker_validator (#179)
- [x] bundle validator (#231)
- [x] transaction_solidifier (#378)

**Comment by tsvisabo** [comment]
done
