### ISSUE TITLE
Cpplint compatible problem

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/entangled#213]
### Python version on my machine:
* python3: 3.6.4
* python2: 2.7.15rc1

The `cpplint.py` we're using now is not compatible with python3, but even if I changed using python2 or clone the latest version ([cpplint repo](https://github.com/cpplint/cpplint)) of `cpplint.py` which is compatible with python3, 
I'll get the below error messages:

```
/home/jkrvivian/IOTA/entangled/cppclient/beast.h:8:  #ifndef header guard has wrong style, please use: IOTA_ENTANGLED_CPPCLIENT_BEAST_H_  [build/header_guard] [5]
/home/jkrvivian/IOTA/entangled/cppclient/beast.h:40:  #endif line should be "#endif  // IOTA_ENTANGLED_CPPCLIENT_BEAST_H_"  [build/header_guard] [5]
Done processing /home/jkrvivian/IOTA/entangled/cppclient/beast.h
Done processing /home/jkrvivian/IOTA/entangled/cppclient/beast.cc
Done processing /home/jkrvivian/IOTA/entangled/cppclient/api_json.cc
/home/jkrvivian/IOTA/entangled/cppclient/api_json.h:8:  #ifndef header guard has wrong style, please use: IOTA_ENTANGLED_CPPCLIENT_API_JSON_H_  [build/header_guard] [5]
/home/jkrvivian/IOTA/entangled/cppclient/api_json.h:82:  #endif line should be "#endif  // IOTA_ENTANGLED_CPPCLIENT_API_JSON_H_"  [build/header_guard] [5]
Done processing /home/jkrvivian/IOTA/entangled/cppclient/api_json.h
/home/jkrvivian/IOTA/entangled/cppclient/tests/beast.cc:8:  <chrono> is an unapproved C++11 header.  [build/c++11] [5]
/home/jkrvivian/IOTA/entangled/cppclient/tests/beast.cc:10:  <thread> is an unapproved C++11 header.  [build/c++11] [5]
Done processing /home/jkrvivian/IOTA/entangled/cppclient/tests/beast.cc
/home/jkrvivian/IOTA/entangled/cppclient/tests/api_json.cc:8:  <chrono> is an unapproved C++11 header.  [build/c++11] [5]
/home/jkrvivian/IOTA/entangled/cppclient/tests/api_json.cc:11:  <thread> is an unapproved C++11 header.  [build/c++11] [5]
Done processing /home/jkrvivian/IOTA/entangled/cppclient/tests/api_json.cc
/home/jkrvivian/IOTA/entangled/cppclient/api.h:8:  #ifndef header guard has wrong style, please use: IOTA_ENTANGLED_CPPCLIENT_API_H_  [build/header_guard] [5]
/home/jkrvivian/IOTA/entangled/cppclient/api.h:109:  #endif line should be "#endif  // IOTA_ENTANGLED_CPPCLIENT_API_H_"  [build/header_guard] [5]
/home/jkrvivian/IOTA/entangled/cppclient/api.h:11:  <chrono> is an unapproved C++11 header.  [build/c++11] [5]
Done processing /home/jkrvivian/IOTA/entangled/cppclient/api.h
/home/jkrvivian/IOTA/entangled/cppclient/messages.h:8:  #ifndef header guard has wrong style, please use: IOTA_ENTANGLED_CPPCLIENT_MESSAGES_H_  [build/header_guard] [5]
/home/jkrvivian/IOTA/entangled/cppclient/messages.h:51:  #endif line should be "#endif  // IOTA_ENTANGLED_CPPCLIENT_MESSAGES_H_"  [build/header_guard] [5]
Done processing /home/jkrvivian/IOTA/entangled/cppclient/messages.h
Total errors found: 13
```

Do we need specific python version to pass this check?
Or maybe we need to fix these errors?

**Comment by thibault-martinez** [comment]
Hi @jkrvivian , I don't think python version has anything to do with the results.

For the headers errors, it's because you are in a `IOTA/entangled` folder and not just `entangled`, cpplint wants the headers to be perfectly scoped.

@tsvisabo Do you have an idea why `<chrono>` and `<thread>` would be `unapproved C++11 header` ?

**Comment by oopsmonk** [comment]
@jkrvivian it's not related to python version, but the `cpplint.py` policy. 
The `<chrono>`and`<thread>` are banned at `cpplint.py` in [google/styleguide](https://github.com/google/styleguide/blob/gh-pages/cpplint/cpplint.py#L5843-L5853) and [cpplint/cpplint](https://github.com/cpplint/cpplint/blob/master/cpplint.py#L6002-L6012), but not in [iotaledger/entangled](https://github.com/iotaledger/entangled/blob/develop/tools/cpplint.py#L5843-L5851) 
I guess the reason is in [Chromium](https://chromium-cpp.appspot.com/)

> `<chrono>`  Overlaps with Time APIs in base/. Keep using the base/ classes.
> `<thread>` Overlaps with many classes in base/. Keep using the base/ classes for now.

**Comment by jkrvivian** [comment]
@thibault-martinez  @oopsmonk , thanks!

But there's no output when running `cpplint` in [iotaledger/entangled](https://github.com/iotaledger/entangled/blob/develop/tools/cpplint.py#L5843-L5851) with python3.
The git hook process will stop here when running this check without any messages.

```
jkrvivian:cppclient $ git commit -m "tmp"
[Autohook] Looking for pre-commit scripts to run...found 3!
[Autohook] BEGIN 01-buildifier-check
[Autohook] FINISH 01-buildifier-check
[Autohook] BEGIN 02-cpplint
jkrvivian:cppclient $ 
```

**Comment by thibault-martinez** [comment]
@jkrvivian Is this still an issue ?

**Comment by thibault-martinez** [comment]
@jkrvivian I'll close this in a couple of days if it's not an issue anymore.

**Comment by jkrvivian** [comment]
@thibault-martinez ,thanks! Let's close it.
