### ISSUE TITLE
Compress signature_or_message (iota_transaction) in DB

### ISSUE THREAD

**Issue by tsvisabo** [iotaledger/entangled#218]
`signature_or_message ` that is `9999999....99` should be represented as an empty string,
Also `SOMETHING9...999` ->  `SOMETHING`
In general: 
^([A-Z9]*[A-Z])?9*  ---> capture group 1

**Comment by thibault-martinez** [comment]
Maybe we can omit some ending 9s in tx hashes as well ?

**Comment by tsvisabo** [comment]
Not sure how much it will save, how many `9` are in average in a transaction end..

**Comment by thibault-martinez** [comment]
MWM / 3 so it's about 6% of the hash field

**Comment by tsvisabo** [comment]
yeah, i guess we could do that as well
