### ISSUE TITLE
Checking the commit hook on CI. 

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/entangled#230]
Don't know if contributors have run the commit hook before a commit. We should check it on CI.

**Comment by thibault-martinez** [comment]
Method used for the C++ lib : https://github.com/thibault-martinez/iota.lib.cpp/blob/master/.travis.yml#L243

**Comment by oopsmonk** [comment]
if I am right, need to add clang-format in [Dockerfile](https://github.com/th0br0/iota-buildenv/blob/master/Dockerfile) and a new step in [pipeline.yml](https://github.com/iotaledger/ci-pipelines/blob/master/entangled-prs/pipeline.yml).
