### ISSUE TITLE
Setup cIRI database with bazel

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#234]
Either we ask the user to generate the database as part of the building process (something like `sqlite3 ciri/ciri.db < common/storage/sql/schema.sql`) either bazel does it under the hood.
Issue is that bazel generated files are read-only, so as a temporary solution we pushed a database (`ciri/ciri.db`) containing nothing but the schemas and bazel does a link to it, user has nothing to do but there is a redundancy between the database and the schema (located under `common/storage/sql/schema.sql`)

**Comment by th0br0** [comment]
Why don't we just initialise the database as part of the initial run if it can't be found?

**Comment by thibault-martinez** [comment]
Initialise the database from bazel or from cIRI itself ?

**Comment by th0br0** [comment]
cIRI itself. Woudl need access to the schema I guess.

**Comment by thibault-martinez** [comment]
It has been decided to ask the user to generate the database. See README.
