### ISSUE TITLE
No idea what this repo does.

### ISSUE THREAD

**Issue by l3wi** [iotaledger/entangled#269]
### Issue
Looking at this repo and it's readme, tagline or tags I have no idea of the following:
1. What this repo is (apart from being a monorepo)
2. What the repo contains
3. What each folder does 
a. how to build each folder (except ccurl)
b. how the folder relates to each other folder 
c. folder's state of progress
d. folder's versioning

### Suggestions
1. `enTangle'd is an amalgamation of all things Tangle` is less than descriptive
  a. Suggest change to: `This is a monorepo containing all you need get IOTA operating in C`
  b. Meta overview of what this repo is, what is contains and its aims.
2. List what the repo contains
  a. Better descriptive tags for search-ability: `c` `c++` `c library`
  b. Create a `monoreadme`™ about the `monorepo` 
    - H3 Title for each folder
    - Two sentence paragraph describing the function of the folder
    - State of development (Active, abandoned, deprecated)
3. Readme in each folder containing:
  a. General description of the folder's content.  Copy pasta of the `monoreadme`™ description is fine if descriptive enough
  b. How to build each folder. If no build needed then list that.
  c. List how this folder depends on another folder in the repo
  d. The date of the latest commit and the version number (if one) of that commit. Preferably directly below the title and description. 
  e. If the folder is actively being developed or if its deprecated. 

I'm happy to assist on formatting

**Comment by oopsmonk** [comment]
Right, this project seems still has uncertainty about architectures, need more detail for someone who is willing to contribute about subprojects. For Cclient subproject, after designing extended API calls should be a good time to write the README.md.

**Comment by rajivshah3** [comment]
Slightly off topic, but the repo also doesn't have a license. Considering this repo is now pinned on the iotaledger organization page, it's more prominent and should probably have a license
