### ISSUE TITLE
Add general module or use none for generic errors

### ISSUE THREAD

**Issue by tsvisabo** [iotaledger/entangled#295]
RC_CONSENSUS_NULL_PTR
RC_CONSENSUS_NULL_BUNDLE_PTR
RC_NEIGHBOR_NULL_URI
RC_NEIGHBOR_NULL_HASH
RC_NEIGHBOR_NULL_PACKET
RC_NEIGHBOR_NULL_NODE

and many more, how many of these should be just `RC_NULL_PTR`?
@thibault-martinez  / @th0br0

**Comment by oopsmonk** [comment]
and `RC_OOM` for these?
RC_STORAGE_OOM
RC_CCLIENT_OOM
RC_CONSENSUS_OOM
RC_RESPONDER_COMPONENT_OOM
RC_SNAPSHOT_OOM

**Comment by thibault-martinez** [comment]
I have done some in a recent PR, I'll double check and close this issue.
