### ISSUE TITLE
CClient: identify good abstraction for arrays

### ISSUE THREAD

**Issue by th0br0** [iotaledger/entangled#35]
you need to allocate the actual array first before putting it into a struct for consumption by cclient. This is not very nice...

**Comment by oopsmonk** [comment]
It is implemented in PR https://github.com/iotaledger/entangled/pull/169
Cclient uses [utarray macro](https://troydhanson.github.io/uthash/utarray.html) and `char_buffer` to allocate the real size as needed.

**Comment by thibault-martinez** [comment]
Closed by #169
