### ISSUE TITLE
Reusability of storage prepared statements

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#357]
We currently have to recompute storage prepared statements due to some parameters (mostly integers) not being bound. When all parameters will be bound, we can add some sort of state to reuse prepared statements.

**Comment by th0br0** [comment]
Note that this needs some kind of TLS due to concurrency - or a per-thread stateful instance of storage :thinking:

**Comment by thibault-martinez** [comment]
- SQLITE_THREADSAFE=<0 or 1 or 2> (https://www.sqlite.org/compile.html#threadsafe)

> This option controls whether or not code is included in SQLite to enable it to operate safely in a multithreaded environment. The default is SQLITE_THREADSAFE=1 which is safe for use in a multithreaded environment. When compiled with SQLITE_THREADSAFE=0 all mutexing code is omitted and it is unsafe to use SQLite in a multithreaded program. When compiled with SQLITE_THREADSAFE=2, SQLite can be used in a multithreaded program so long as no two threads attempt to use the same database connection (or any prepared statements derived from that database connection) at the same time.
To put it another way, SQLITE_THREADSAFE=1 sets the default threading mode to Serialized. SQLITE_THREADSAFE=2 sets the default threading mode to Multi-threaded. And SQLITE_THREADSAFE=0 sets the threading mode to Single-threaded.

- SQLITE_CONFIG_SERIALIZED (https://www.sqlite.org/c3ref/c_config_covering_index_scan.html#sqliteconfigserialized)

> There are no arguments to this option. This option sets the threading mode to Serialized. In other words, this option enables all mutexes including the recursive mutexes on database connection and prepared statement objects. In this mode (which is the default when SQLite is compiled with SQLITE_THREADSAFE=1) the SQLite library will itself serialize access to database connections and prepared statements so that the application is free to use the same database connection or the same prepared statement in different threads at the same time. If SQLite is compiled with the SQLITE_THREADSAFE=0 compile-time option then it is not possible to set the Serialized threading mode and sqlite3_config() will return SQLITE_ERROR if called with the SQLITE_CONFIG_SERIALIZED configuration option.

**Comment by thibault-martinez** [comment]
Closed by #656
