### ISSUE TITLE
utils/hash_containers - refactor 

### ISSUE THREAD

**Issue by tsvisabo** [iotaledger/entangled#400]
* implement each container into it's own file

* functions should be implemented as static in header files

**Comment by howjmay** [comment]
Hi I am working on this issue. Should I add an unit test for each container?
And do I need to implement each containers for concurrent  or transaction_request which have been implemented in `utils/containers/queue` ?
Thank you for answering!

**Comment by th0br0** [comment]
Hey @HowJMay,
at the moment the containers in https://github.com/iotaledger/entangled/blob/master/utils/hash_containers.c are single-threaded, so don't worry about concurrency here. 
Unit tests would be welcome of course!

**Comment by tsvisabo** [comment]
@HowJMay  Hey! this issue is now fixed, but if you had any other improvements/test you would like to Merge, please open a PR
Fixed by #439
