### ISSUE TITLE
Implement get_balances

### ISSUE THREAD

**Issue by th0br0** [iotaledger/entangled#45]

**Comment by howjmay** [comment]
@oopsmonk hi I am working on implementing get_balances api.
I wonder how can I test it?

**Comment by oopsmonk** [comment]
@HowJMay the key part is serialization, you should write code in `test_serialize_get_balances` and `test_deserialize_get_balances` to test your implementation. if you wanna test the API, you can create a bazel project to test your API. [here](https://github.com/iotaledger/entangled/pull/169) is an example for `iota_api_find_transactions`

**Comment by howjmay** [comment]
Thank you. I will give it a try

**Comment by thibault-martinez** [comment]
Closed by #216
