### ISSUE TITLE
transaction_solidifier - refactor

### ISSUE THREAD

**Issue by tsvisabo** [iotaledger/entangled#453]
Currently `iota_consensus_transaction_solidifier_check_solidity` is being called every time a milestone arrives and  triggers solidity check (DFS)
We could instead get rid of this method, therefor, only when a transaction is being processed we trigger a solidity check,
that solidity check will traverse from the new transaction into its past, if none of the transactions are missing, then, as we do today, those transactions should be set solid, otherwise they should all be added to a set of *missing_and_requested_transactions*,
to avoid long DFS traversals, the solidity check do_func will make sure not to branch if the current transaction is already in the set.

**Comment by th0br0** [comment]
Where would you store these `missing_and_requested_transactions`?

**Comment by tsvisabo** [comment]
In `transaction_solidifier_t`?

**Comment by th0br0** [comment]
So in-memory :thinking: that set probably has to be bounded then

**Comment by tsvisabo** [comment]
It could not ever exceed Tangle's size :)
