### ISSUE TITLE
ciri: rebuild tx-to-request list on startup

### ISSUE THREAD

**Issue by th0br0** [iotaledger/entangled#495]
At the moment, we start with an empty list.
Instead, we should look at which tx we're still missing (maybe bounded?)

Can be populated by a simple SQL query on startup with a limit attached, e.g.

```
sqlite> SELECT trunk, branch FROM iota_transaction a WHERE NOT(EXISTS(SELECT 1 FROM iota_transaction b WHERE b.hash = a.trunk OR b.hash = a.branch));
99IJGVQYSYSIWSHQUAVPFYSDSPTAFESJL9AQOZMQMHBIVDWSP9ASHARQNWPIRQTVTRUQSEKANSQS|SVUGXXILYJOVQBQMJJK9RLHTDNWYQYEFBCQYWFKDDOADNQEYWONQTYXDXGEPJBYFKGTWZTXDL9CSA
```

Needs uniqueness filtering afterwards

**Comment by thibault-martinez** [comment]
Note that the transaction_requester queue is currently bounded by `#define MAX_TX_REQ_NBR 10000`.
