### ISSUE TITLE
Implement/Design `init_iota_http_service`

### ISSUE THREAD

**Issue by tsvisabo** [iotaledger/entangled#55]

**Comment by jkrvivian** [comment]
Hi, @tsvisabo 
I would like to implement `init_iota_http_service`, there're two TODO  comments about this function.
1. **TODO: implement + figure a way to pass serializer/serializer_enum and other**
I think we can call `init_json_serializer` for serializer, but I'm not sure about other fields like `content_type`, `version` and  `timeout`. Should we give the default value directly?

2. **TODO: params, should they be loaded from conf?**
I think it's OK that host and port are loaded from parameters :smile:

**Comment by tsvisabo** [comment]
Hi @jkrvivian , first, thanks!
i think that all parameters should be configurable, you should discuss @oopsmonk

**Comment by oopsmonk** [comment]
I am not sure if we need `init_iota_http_service`, but I prefer to have `init_iota_client` which do all init stuff. I think, cclient is a library that fetches configuration via parameters, so we don't need a configure file.
