### ISSUE TITLE
Model/bundle: About bundle finalization

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/entangled#613]
Now we have `calculate_bundle_hash` to get bundle hash, 
I think a `bundle_finalize` function to fill in bundle hash through transactions is also needed.

Any idea?

**Comment by thibault-martinez** [comment]
Hi @jkrvivian, transfers might be what you are looking for

https://github.com/iotaledger/entangled/blob/develop/common/model/transfer.c
https://github.com/iotaledger/entangled/blob/develop/common/model/transfer.h

Also have a look at examples/tests

https://github.com/iotaledger/entangled/blob/develop/common/model/tests/test_transfer.c

There's a `transfer_ctx_hash` function there

**Comment by th0br0** [comment]
Hey! It's definitely needed (even if just as a helper) :) 
Feel free to submit a PR?

**Comment by jkrvivian** [comment]
@th0br0 sure! I'm glad to help.

**Comment by oopsmonk** [comment]
PR #665 is a quick/ugly implementation, it needs optimizations on Kerl instance and flex_trit conversions.
