### ISSUE TITLE
cclient: JVM related fields are absent in get_node_info response.

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/entangled#628]
JVM fields in get_node_info were removed in #606, need to put them back that the cclient can talk with IRI.

**Comment by th0br0** [comment]
Can't we make cclient reading optional?

**Comment by th0br0** [comment]
(to be honest, I'm fine with cclient not reading these fields at all)

**Comment by oopsmonk** [comment]
We can show these fields when they are present, but not remove them.

**Comment by th0br0** [comment]
What about supporting a core set of fields and then adding some dynamic (&optional) key/value parsing of the rest with some map-like access?

**Comment by Citrullin** [comment]
Why do we provide jvm information for the client in the first place? I mean the node_info should be independent of the used language. So, I would just drop the support. Maybe that is also a topic for IF talk. Dropping the values in IRI/cIRI as well.

**Comment by oopsmonk** [comment]
In the beginning, the response follows the Response examples in [documentation](https://docs.iota.org/docs/iri/0.1/references/api-reference). I agree, the Java fields are meaningless for the cIRI/cclient.
