### ISSUE TITLE
bundle: add test that compares calculated bundle hash against existing mainnet bundle

### ISSUE THREAD

**Issue by th0br0** [iotaledger/entangled#674]
- we don't test against example bundles right now 
- we need a test that validates that computed normalised bundle hash is 13-free

**Comment by tsvisabo** [comment]
we now do:
https://github.com/iotaledger/entangled/tree/develop/consensus/bundle_validator/tests

**Comment by thibault-martinez** [comment]
Check that all the following cases are covered:
```
BUNDLE_VALID,
BUNDLE_EMPTY,
BUNDLE_INCOMPLETE,
BUNDLE_INVALID_TX,
BUNDLE_INVALID_INPUT_ADDRESS,
BUNDLE_INVALID_VALUE,
BUNDLE_INVALID_HASH,
BUNDLE_INVALID_SIGNATURE
```
