### ISSUE TITLE
common: loaded_columns_mask in transaction object.

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/entangled#683]
The `loaded_columns_mask` flag is not set in transaction_set_* methods. 
E.g. 
add `MASK_DATA` in `transaction_set_message`.
clear `loaded_columns_mask` in `transaction_reset`

Maybe we should extend it to 32 bits and check all fields in the transaction object, so we can check all fields are set in a proper way.
E.g. 
```
MASK_ESSENCE = MASK_ESSENCE_ADDRESS | 
   MASK_ESSENCE_VALUE | MASK_ESSENCE_OBSELETE_TAG 
   ....
```

**Comment by th0br0** [comment]
Good catch; we probably need to do a per-field bitmask
