### ISSUE TITLE
Expose batched PoW method

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/entangled#690]
The current exposed PoW function operates on a single tryte string with its trunk & branch transaction. This can lead to performance issues in js based apps e.g. Trinity Mobile. 

We need to expose a method that accepts bundle trytes with trunk & branch fetched from gTTA, performs proof-of-work for all trytes, assigns the correct nonce and returns the updated trytes. Android bindings would also need to be written.

A similar function can be found here in js: https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/libs/iota/transfers.js#L865-L923 and here in obj c/java https://github.com/iotaledger/trinity-wallet/pull/134/files#diff-972b2fe267f780e30392b2725174ac8bR20.

**Comment by th0br0** [comment]
This is fixed via #700.
