### ISSUE TITLE
Compilation of a project linked against entangled fails

### ISSUE THREAD

**Issue by kuhlmannmarkus** [iotaledger/entangled#696]
While compiling a project that is linked against entangled I receive this error:

```
In file included from /data/entangled/common/curl-p/hamming.h:12:0,
                 from /data/entangled/mam/v1/mam.h:11,
                 from src/testapp/main.cpp:8:
/data/entangled/common/curl-p/trit.h:32:1: error: expected declaration before ‘}’ token
 };
 ^
```

This was not the case in [develop] mam1: fix failing security tests (#560) (3910db7ce4db7d448d5d33b43e3a1568f4fcf19c)

**Comment by thibault-martinez** [comment]
Hi @kuhlmannmarkus, thanks for reporting this.
I see the issue, I'll provide a fix ASAP.

**Comment by thibault-martinez** [comment]
@kuhlmannmarkus Could you check if 48a9237143f178b02775eb499758b9244ebbc891 fixed it ? I'll let you close the issue if yes.

**Comment by kuhlmannmarkus** [comment]
I can confirm https://github.com/iotaledger/entangled/commit/48a9237143f178b02775eb499758b9244ebbc891 solves the problem. Thank you!
