### ISSUE TITLE
cclient: support HTTPS connections

### ISSUE THREAD

**Issue by th0br0** [iotaledger/entangled#724]
Many IRI nodes are only exposed via HTTPS nowadays.
We should strive to support this as well.

**Comment by oopsmonk** [comment]
IMO, there is no benefit for adding HTTPS on IoT devices, considering the implementation and performance.

**Comment by marko-k0** [comment]
> IMO, there is no benefit for adding HTTPS on IoT devices, considering the implementation and performance.

Could [libcoap](https://github.com/obgm/libcoap) be used? And if not, why not?

**Comment by th0br0** [comment]
> IMO, there is no benefit for adding HTTPS on IoT devices, considering the implementation and performance.

We should still support it as an alternative backend, not all cclient use cases will happen in embedded environments. 

> Could [libcoap](https://github.com/obgm/libcoap) be used? And if not, why not?

COAP is sth quite different from HTTP. Without IRI (or other IOTA nodes) supporting it that doesn't make sense right now.

**Comment by marko-k0** [comment]
> We should still support it as an alternative backend, not all cclient use cases will happen in embedded environments.

Ok. Questions:
1. Should specifying whether it's a SSL/TLS or plain HTTP connection be a responsibility of a API user? Or we should try HTTPS first and failback to HTTP?
2. Every API call creates a new socket. Is it expected that a node closes a socket after every response to a client or this could be changed so the cclient reuses existing socket?

> COAP is sth quite different from HTTP. Without IRI (or other IOTA nodes) supporting it that doesn't make sense right now.

My thoughts were if this could/should/will be added in general - also to IRI.

**Comment by kuhlmannmarkus** [comment]
> > IMO, there is no benefit for adding HTTPS on IoT devices, considering the implementation and performance.
> 
> We should still support it as an alternative backend, not all cclient use cases will happen in embedded environments.
> 
> > Could [libcoap](https://github.com/obgm/libcoap) be used? And if not, why not?
> 
> COAP is sth quite different from HTTP. Without IRI (or other IOTA nodes) supporting it that doesn't make sense right now.

I totally agree with @th0br0. HTTPS connections will be extremely useful.
