### ISSUE TITLE
Determine sprint naming scheme.

### ISSUE THREAD

**Issue by th0br0** [iotaledger/entangled#728]

**Comment by thibault-martinez** [comment]
- Food (Houmous, Tofu... totally not biased)
- Material (Iron, Wood...)
- Mathematicians / Physicists (Poincaré, Riemann...)

**Comment by oopsmonk** [comment]
Cuisines around the world: a-gei, bratwurst, poutine, cassoulet, falafel...

**Comment by th0br0** [comment]
As we've got two votes - looks like it's bratwurst for the next sprint!
