### ISSUE TITLE
"Transaction" name clash in cppclient

### ISSUE THREAD

**Issue by ifullgaz** [iotaledger/entangled#78]
Transaction is defined as a struct in cppclient (api.h) as well as a class in common/model (cpptransaction.h).
Although they are in different namespaces, it is impossible to use both non-namespaces names together in the same source file.
See api_json.cc for an example where the fully qualified name of the Transaction class was used.

**Comment by thibault-martinez** [comment]
Looks like this has been fixed for a long time.
