### ISSUE TITLE
mam2: check uniqueness of nonces

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#783]
> One more thing about nonces.
There are quite hard restrictions on nonces in the spec although they may not be clearly stated.
Nonces must be unique. And it might be difficult for end-users to provide such unique values.
For example, channel name is an input value to the CreateChannel.
But it should not be reused.
Also, endpoint mss is generated using nonce `ch_name || ep_name`.
But what if `ch1_name || ep1_name = ch2_name || ep2_name`.
Logically that would be two different endpoints, but with completely identical keys.
As WOTS keys must not be reused, it might lead to a complete compromise of endpoint.
So what I'm trying to say is that there must be some additional logic/checks to prevent that.

**Comment by tsvisabo** [comment]
Fixed via #956
