### ISSUE TITLE
General: Remove IDE specific gitignore

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/entangled#800]
It is the best practice to not include IDE specific directories into the .gitignore file of the repository. 
The gitignore should be independent in any way. Therefore, it should not include any information about the operation system or IDE.
Better: Use a local global .gitignore. Github has also an [article](https://help.github.com/articles/ignoring-files/) about this. 

What do you think about removing everything which is not necessary for the repository?

**Comment by thibault-martinez** [comment]
Hi @Citrullin, while I don't have a strong opinion on this, I still think that having a repository `.gitignore` including the main OS and IDE related files is a good thing to avoid having polluted PRs by developpers that don't have a local `.gitignore`.
On the other hand, I agree that we could order our `.gitignore` a little bit more clearly.

**Comment by Citrullin** [comment]
@thibault-martinez Simple as that: Decline PRs which are polluted and post a link as friendly reminder. The github article is really useful for this :) Maybe it makes also sense to add this to the contribution guide.

**Comment by thibault-martinez** [comment]
Of course, but I personally don't think that is bad practice at all.

**Comment by oopsmonk** [comment]
it's a good practice, let's sort it out in #809
