### ISSUE TITLE
Fix 32bit compatibility

### ISSUE THREAD

**Issue by th0br0** [iotaledger/entangled#81]
- [ ] Fix 32bit compatibility issues
- [ ] Enable CI build & tests with i686 bootlin toolchain

**Comment by oopsmonk** [comment]
For this issue, setup a 32bit VM and run bazel test on 32bit VM is necessary.
I tried to build bazel for 32bit platform,but it failed, regard with bazel not support 32bit platform. 
https://github.com/bazelbuild/bazel/issues/1340
A workaround for this is to collect all test binaries, and running those on a 32bit VM, but it is not a good solution for CI.

**Comment by oopsmonk** [comment]
closed this in https://github.com/iotaledger/entangled/pull/109
