### ISSUE TITLE
cIRI: Cached neighbors?

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/entangled#812]
I changed the UDP protocol of a neighbor to TCP. I changed the yaml file, restarted the node. The port is also changed now.

In my yaml file:
```yaml
neighbors: "tcp://***.**.77.50:14600 tcp://www.****.us:14600 tcp://*****.ddns.net:14600 tcp://***.***.223.97:15600 tcp://****.*****.org:14600"
```

```bash
2019-02-13 11:29:30:tcp_receiver_service:   INFO: Connection denied with non-tethered neighbor tcp://***.***.223.97:14600
2019-02-13 11:29:30:tcp_receiver_service:   INFO: Connection lost with tethered node tcp://***.***.223.97:14600
```

Could it be, that the neighbors are cached somewhere?

**Comment by thibault-martinez** [comment]
https://github.com/iotaledger/entangled/issues/223 maybe ?

**Comment by Citrullin** [comment]
@thibault-martinez Interesting. I should change the dns named one with the IP address then. But the one which failed is an IP address :)
