### ISSUE TITLE
cIRI: Disable Snapshot validation via parameter

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/entangled#813]
It would be nice to have a command line argument or config option to disable the snapshot validation. That is especially helpful when you just try some changes.

**Comment by alon-e** [comment]
you can actually do this by `--snapshot-signature-file ""` which will skip the validation code path - not sure if this is a bug; I opened an issue about it: #964

**Comment by thibault-martinez** [comment]
@alon-e Do you think we shouldn't allow running cIRI without signature validation on Mainnet even with a strongly unambiguous `--skip-signature-validation` CLI option ?
