### ISSUE TITLE
common: investigate all MSVC compilation errors

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#827]
> By the way guys, what do you say to making a few changes to the entangled so it's possible to compile it with msvc? I'm talking about `inline` (msvc does not understand that) and changing `min` to `min__` in `trits.c` (although `NOMINMAX` is defined msvc somehow manages to define both `min` and `__min`; how pathetic).

**Comment by th0br0** [comment]
What's the source for this?

This is a wontfix. MSVC doesn't even support C99 properly - e.g. VLA which we use in quite a few places and a few other things. People wanting to build entangled on Windows should just use clang.

rel https://stackoverflow.com/questions/48615184/does-visual-studio-2017-fully-support-c99
