### ISSUE TITLE
CClient: sturcture padding issue on ESP32 platfrom

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/entangled#828]
As ESP32 platform, data is forced to be 4 bytes alignment, therefore the member of a structure need to consider paddings.
For instance, the size of `get_node_info_res_t` is 296, the real size shoulde be 283 using `FLEX_TRIT_ENCODING_3_TRITS_PER_BYTE`, 13 bytes is padded on it.
We can reduce memory usage and a potential access problem on this structure via changing member order, shown below.
```
typedef struct get_node_info_res_s {
  char_buffer_t* app_name;
  char_buffer_t* app_version;
  uint32_t latest_milestone_index;
  uint32_t latest_solid_subtangle_milestone_index;
  uint32_t milestone_start_index;
  uint32_t tips;
  uint32_t transactions_to_request;
  uint16_t packets_queue_size;
  uint16_t neighbors;
  uint64_t time;
  flex_trit_t latest_milestone[FLEX_TRIT_SIZE_243];
  flex_trit_t latest_solid_subtangle_milestone[FLEX_TRIT_SIZE_243];
  flex_trit_t coordinator_address[FLEX_TRIT_SIZE_243];
} get_node_info_res_t;
```
The structure size is 288 bytes which are 5 bytes padded only.
We need to review and make sure structures are all aligned properly.

**Comment by thibault-martinez** [comment]
Closed by #958
