### ISSUE TITLE
mam2: various notes and bugs

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/entangled#835]
- [x] `mam_wots_t` remove `spongos` field, it is volatile and can be instantiated locally in functions `mam_wots_xxx`. Rename `mam_wots_t` to `mam_wots_sk_t`.
- [x] `mam_channel_t` `name` convert to a _fixed size_ field like `trit_t name[MAM2_CHANNEL_NAME_SIZE]`; fixed size will have an advantage that the prefix can be statically defined; same for `mam_endpoint_t`.
- [x] TODO: update the way nonces are absorbed.
- [x]  TODO: add trusted pks.
- [x]  TODO: automatically deal with `chid1`, `epid1` - make them trusted?
- [x]  `ERR_GUARD_RETURN` don't need third `e` argument - it can directly `return err;`. Thus many functions won't need `e` variable.
- [x]  Rename `enpoint` typo to `endpoint`.
- [x]  Use `prng_destination_tryte_t` type for `destination` argument in `mam_prng_genX` functions?
- [x]  Use a secure variant of `memset` in `xxx_destroy` functions to clean secret keys. `memset` is considered unsafe and may be trown out by the compiler. See https://wiki.sei.cmu.edu/confluence/display/c/MSC06-C.+Beware+of+compiler+optimizations
- [x]  If `mam_endpoint_create` fails should `mam_endpoint_destroy` be called? If not that may lead to memleak (for example, if `mss_create` fails `endpoint->name` will not be freed).
- [x]  `trits_free` can't be called twice with the same argument; it requires careful use or manual nullification of trits (`trits_free(x); x = trits_null();`). Better change to `void trits_free(trits_t *x)` or add nullification after each call to `trits_free` (see `mam_endpoint_destroy`).
- [x]  `pb3_sizeof_size_t` takes size in _trytes_ as it usually encodes size of the following `trytes` (except when it encodes `repeated` count). In `mam_endpoint_serialized_size` it is called with `mss_size` which is size in _trits_, just call `pb3_sizeof_size_t(mss_size / 3)`. Similar in other places. In `xxx_deserialize` `pb3_decode_size_t` should return size in _trytes_ hence `trits_alloc` should be called with `3 * size`.
- [x]  Maybe make `mss_serialize` take `trits_t *buffer` and return `buffer` after the end of serialized data?
- [x]  `mam_endpoint_serialize` always returns `RC_OK`. Makes sense to change return type to `void` or to add runtime check of `buffer`?
- [x]  If `mam_endpoint_deserialize` fails allocated memory will not be freed.
- [x]  `mam_msg_recv_context_t` can declare `chid`, `chid1`, `epid`, epid1` in nested union.
- [x]  `mam_msg_recv_packet_context_t`, `mam_msg_recv_context_t` remove fields `spongos_wots`, `spongos_mss`; they are volatile and can be defined directly at the use site - in `mss_verify` (`mss_sign` is partly), thus many functions would take 2 arguments less.
- [x]  `mam_msg_recv_context_t` fields `psks` and `ntrus` should be arguments to `mam_msg_recv`.
- [x]  `mam_msg_recv_packet_context_t` and `mam_msg_recv_context_t` should be the same.
- [x]  In `mam_api_init` funny cast of `mam_seed` to `char const *`. Change type of `mam_seed` to `char const *`?
- [x]  `mam_prng_init` should return void.
- [x]  `xxx_destroy` should return void (as there is no way to handle errors in destructors)?
- [x]  `message_part.p + message_part.d` -> `trit_t *trits_ptr(trits_t x)`. Or `trits_begin(x) = x.p + x.d;` and `trits_end(x) = x.p + x.d + x.n;`.
- [x]  `MAM2_TRITS_DEF0(payload_trits, strlen(payload) * 3);` allocates memory on stack, might overflow; better use `trits_alloc`. Better yet payload can be encrypted in a buffered manner - no need to convert to trits the whole `payload`.
- [x]  `ctx->ord++`: last packet must be encoded as a negative value. Dirty hack but that's the spec.
- [x]  `cfg.psks = api->ntru_pks;` it's just wrong.
- [x]  `msg.d` -> `size_t trits_dropped_size(trits_t x) { return x.d; }`
- [x]  `msg = trits_drop(msg, NUM_TRITS_SIGNATURE - msg.d);` how is that supposed to work?
- [x]  TODO: send/recv packet split into 3 functions: head, payload, tail; or modify them so they take payload as `flex_trit_t *`?
- [x]  `num_trits_in_bundle` unused in `mam_api_bundle_read_packet`.
- [x]  You can detect presence of packet after header in bundle by nonzero `ord`.
- [x] Need to verify the use of `trits_is_overlapped` in the code.
- [x] Need to fix asserts in `trits_diff`.
- [x] Replicate https://github.com/iotaledger/mam-specification/commit/31635f372325fb5579a342314892ca4735d91ea6

**Comment by tsvisabo** [comment]
`* `mam_channel_t` `name` convert to a _fixed size_ field like `trit_t name[MAM2_CHANNEL_NAME_SIZE]`; fixed size will have an advantage that the prefix can be statically defined; same for `mam_endpoint_t`.`
Let's have that as a separate issue (counters?)

**Comment by thibault-martinez** [comment]
Closed in favor of newly opened issues and pull requests.
