### ISSUE TITLE
should implementation of iss.c.inc follow the same way as IRI

### ISSUE THREAD

**Issue by ed2k** [iotaledger/entangled#841]
Comparing to IRI [java crypto implementation](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/crypto/ISSInPlace.java) I see several differences, such as 
order or existence of reset
HASH_TRYTE_VAL(hash, i) picking up three index 
inner loop for iss_kerl_sig_digest() 

and also there is no comparable unit test

**Comment by thibault-martinez** [comment]
Closing because the source of this issue has been fixed in https://github.com/iotaledger/entangled/pull/960
