### ISSUE TITLE
infra: Android CI

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/entangled#858]
The NDK compiler is slightly different, so sometimes macros and constants will be undefined unexpectedly. For example, building `//mobile/android:dummy` now fails because `SIZE_MAX` is undefined:
```
ERROR: /Users/vagrant/git/entangled/utils/BUILD:88:1: C++ compilation of rule '//utils:memset_safe' failed (Exit 1) clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/x86-4.9/prebuilt/darwin-x86_64 -target i686-none-linux-android ... (remaining 30 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
utils/memset_safe.c:21:23: error: use of undeclared identifier 'SIZE_MAX'
  } else if (destsz > SIZE_MAX || count > SIZE_MAX) {
                      ^
utils/memset_safe.c:21:43: error: use of undeclared identifier 'SIZE_MAX'
  } else if (destsz > SIZE_MAX || count > SIZE_MAX) {
                                          ^
2 errors generated.
```

This happens because in some versions of the Android NDK, `SIZE_MAX` is actually defined in `limits.h`. 

For this reason, I think it would be helpful to have a pipeline to make sure that any changes do not cause the Android build to fail. I'd be happy to work on this but I wanted to get other opinions first.

**Comment by th0br0** [comment]
We already build for Android as part of our regular CI process. However, we're using r17c and not r19b, probably warrants an update.

**Comment by rajivshah3** [comment]
In that case this issue can probably be closed. It doesn't really make sense to test against later versions of the NDK in my opinion since those seem to have bugs. 17c is probably the best one to use
