### ISSUE TITLE
CClient: Modify data type of hash, bundle, address and tag from trit array to character array 

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/entangled#89]
In CClient `types/types.h`, the data type of hash, address and tags are defined as trit array.
And these are used in parameters in `request` and `response`.

Since we use trytes in every request, why don't we use character array as the data type?
Otherwise we need to transform trits to trytes in each request.

**Comment by tsvisabo** [comment]
Good point @jkrvivian ,
But this is because trit_array will support `3 trits per tryte`
And it might also be that Node will be able to get a request that is encoded in trit_array
in the  future,

**Comment by jkrvivian** [comment]
Cool!
Now I'm working on JSON serializer #50 , which is packing request to JSON format with cJSON library.
@tsvisabo , does that mean we don't need to consider transforming trits to trytes for further request to present Node?
Since when the Node will support a trit_array request is unknown for now.

**Comment by tsvisabo** [comment]
@jkrvivian 
As long as trit array is configured with `3 trits per tryte`, you get trytes and no need for conversions
IRI implementation will not use trit array, so there will have to be some translation in case of  `4/5 trits per tryte`
still needs to be figured

**Comment by tsvisabo** [comment]
@jkrvivian 
Thanks for your willingness to contribute, that is awesome,  but we have still got some legal clarification we need to make until we are able to accept such big code contributions to our own repositories,

**Comment by jkrvivian** [comment]
@tsvisabo 
Could you give more information or references about `4/5 trits per tryte`?
I could not find any discussion about the issue :thinking: 

Thanks!
