### ISSUE TITLE
ciri: Mainnet Snapshot signature can be subverted by empty string

### ISSUE THREAD

**Issue by alon-e** [iotaledger/entangled#964]
if you pass `--snapshot-signature-file ""` as a flag, the snapshot signature validation will be skipped.
(`strlen == 0`)
https://github.com/iotaledger/entangled/blob/24c42365b558a15fd662108eb27629c1008a8518/consensus/snapshot/snapshot.c#L94-L116

while this may be used as a workaround for testnets, this is also possible to subvert on the mainnet.

**Comment by thibault-martinez** [comment]
Hi @alon-e , thanks for reporting this.
This wasn't planned and will be fixed.
