### ISSUE TITLE
ciri: Support Milestones of higher security level and different hashing function

### ISSUE THREAD

**Issue by alon-e** [iotaledger/entangled#975]
In cIRI you track milestones of security level 1 w/ Curl-P-27.
IRI supports also different hashing functions and higher security level: 
- [x] https://github.com/iotaledger/iri/pull/1041
- [x] https://github.com/iotaledger/iri/pull/1322

This is needed for transitioning to the new Milestone structure supported by Compass.

https://github.com/iotaledger/entangled/blob/43d4bdf20da574d5afbe9e72a5f6360ed50ed03c/consensus/milestone_tracker/milestone_tracker.c#L43-L63

**Comment by thibault-martinez** [comment]
Implemented by #996 and #999
